dilip scannercli test

diff --git a/.github/workflows/trivy-sbom.yaml b/.github/workflows/trivy-sbom.yaml
--- a/.github/workflows/trivy-sbom.yaml
+++ b/.github/workflows/trivy-sbom.yaml
@@ -1,88 +1,134 @@
----
-name: CI
+# ---
+# name: CI
+
+# on:
+#   pull_request:
+#     branches:
+#     - main
+#     - 56098
+#     - releases/**
+#     - main-56098
+#   push:
+#     branches:
+#       - main
+#       - release/**
+#       - 56098
+#   workflow_dispatch:
+
+# jobs:
+#   checkout:
+#     name: Checkout code
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: checkout code
+#         uses: actions/checkout@v4
+#       - name: verify checkout
+#         run: |
+#           pwd
+#           ls -la
+
+#   separate-sbom-generation:
+#     name: SBOM generation
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: checkout code
+#         uses: actions/checkout@v4
+#       - name: verify checkout
+#         run: |
+#           pwd
+#           ls -la
+#       - name: Run Trivy Locally
+#         uses: docker://aquasec/aqua-scanner
+#         with:
+#           args:  trivy fs --reachability --package-json --dotnet-proj \
+#                   --db-repository=registry.aquasec.com/trivy-db:2 \
+#                   --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 \
+#                   --scanners vuln,misconfig,secret \
+#                   --java-db-repository=registry.aquasec.com/trivy-java-db:1 -d  .
+#           # To customize which severities to scan for, add: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
+#           # To enable SAST scanning, add: --sast
+#           # To enable reachability scanning, add: --reachability
+#           # To enable npm/dotnet/gradle non-lock file scanning, add: --package-json / --dotnet-proj / --gradle
+#           # Update Comments
+#         env:
+#           AQUA_KEY: ${{ secrets.AQUA_KEY }}
+#           AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
+#           GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
+#           TRIVY_RUN_AS_PLUGIN: aqua
+#           TRIVY_USERNAME: ${{ secrets.AQUASEC_REGISTRY_USER_ID }}
+#           TRIVY_PASSWORD: ${{ secrets.AQUASEC_REGISTRY_PASSWORD }}
+#           AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
+#           CSPM_URL: https://eu-1.api.cloudsploit.com 
+#       - name: Generate SBOM Locally
+#         id: generate-sbom-local
+#         run: |
+#               export BILLY_SERVER=https://billy.codesec.aquasec.com
+#               curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+#               curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+#               if ! cat install.sh.checksum | sha256sum --check; then
+#               echo "install.sh checksum failed"
+#               exit 1
+#               fi
+#               BINDIR="." sh install.sh
+#               rm install.sh install.sh.checksum
+#               ./billy generate \
+#                --access-token "${{ secrets.TOKEN_GITHUB }}" \
+#                --aqua-key "${{ secrets.AQUA_KEY }}" \
+#                --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+#                --cspm-url https://eu-1.api.cloudsploit.com \
+#                --artifact-path "." 
+
+#                 # The docker image name:tag of the newly built image
+#                 # --artifact-path "my-image-name:${{ env.tag-version }}" 
+#                 # OR the path to the root folder of your project. I.e my-repo/my-app 
+#                 # --artifact-path "${{env.MY_APP_ROOT}}"
+#         env:
+#           AQUA_KEY: ${{ secrets.AQUASEC_API_KEY }}
+#           AQUA_SECRET: ${{ secrets.AQUASEC_API_SECRET }}
+#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
+
+
+name: Download and Execute Binary
 
 on:
-  pull_request:
-    branches:
-    - main
-    - 56098
-    - releases/**
-    - main-56098
-  push:
-    branches:
-      - main
-      - release/**
-      - 56098
   workflow_dispatch:
 
 jobs:
-  checkout:
-    name: Checkout code
+  download-and-execute:
+    name: Download and Execute
     runs-on: ubuntu-latest
-    steps:
-      - name: checkout code
-        uses: actions/checkout@v4
-      - name: verify checkout
-        run: |
-          pwd
-          ls -la
 
-  separate-sbom-generation:
-    name: SBOM generation
-    runs-on: ubuntu-latest
     steps:
-      - name: checkout code
+      - name: Checkout repository
         uses: actions/checkout@v4
-      - name: verify checkout
-        run: |
-          pwd
-          ls -la
-      - name: Run Trivy Locally
-        uses: docker://aquasec/aqua-scanner
-        with:
-          args:  trivy fs --reachability --package-json --dotnet-proj \
-                  --db-repository=registry.aquasec.com/trivy-db:2 \
-                  --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 \
-                  --scanners vuln,misconfig,secret \
-                  --java-db-repository=registry.aquasec.com/trivy-java-db:1 -d  .
-          # To customize which severities to scan for, add: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
-          # To enable SAST scanning, add: --sast
-          # To enable reachability scanning, add: --reachability
-          # To enable npm/dotnet/gradle non-lock file scanning, add: --package-json / --dotnet-proj / --gradle
-          # Update Comments
-        env:
-          AQUA_KEY: ${{ secrets.AQUA_KEY }}
-          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
-          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
-          TRIVY_RUN_AS_PLUGIN: aqua
-          TRIVY_USERNAME: ${{ secrets.AQUASEC_REGISTRY_USER_ID }}
-          TRIVY_PASSWORD: ${{ secrets.AQUASEC_REGISTRY_PASSWORD }}
-          AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
-          CSPM_URL: https://eu-1.api.cloudsploit.com 
-      - name: Generate SBOM Locally
-        id: generate-sbom-local
-        run: |
-              export BILLY_SERVER=https://billy.codesec.aquasec.com
-              curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-              curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-              if ! cat install.sh.checksum | sha256sum --check; then
-              echo "install.sh checksum failed"
-              exit 1
-              fi
-              BINDIR="." sh install.sh
-              rm install.sh install.sh.checksum
-              ./billy generate \
-               --access-token "${{ secrets.TOKEN_GITHUB }}" \
-               --aqua-key "${{ secrets.AQUA_KEY }}" \
-               --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-               --cspm-url https://eu-1.api.cloudsploit.com \
-               --artifact-path "." 
 
-                # The docker image name:tag of the newly built image
-                # --artifact-path "my-image-name:${{ env.tag-version }}" 
-                # OR the path to the root folder of your project. I.e my-repo/my-app 
-                # --artifact-path "${{env.MY_APP_ROOT}}"
+      - name: Download binary
+
+        run: |
+          echo "Downloading binary..."
+          wget --user=nishad.ali@aquasec.com --password=Ahyaan@786 https://download.aquasec.com/scanner/2607.3.5/scannercli
+
+          echo "Binary downloaded successfully"
+
+      - name: Verify downloaded file
+        run: |
+          set -euo pipefail
+
+          ls -lh ./scannercli
+          file ./scannercli
+
+      - name: Make binary executable
+        run: |
+          chmod +x ./scannercli
+
+      - name: Execute Scan
         env:
-          AQUA_KEY: ${{ secrets.AQUASEC_API_KEY }}
-          AQUA_SECRET: ${{ secrets.AQUASEC_API_SECRET }}
-          GITHUB_TOKEN: ${{ secrets.TOKEN }}
+          XYZ_TOKEN: ${{ secrets.XYZ_DOWNLOAD_TOKEN }}
+        run: |
+          set -euo pipefail
+
+          echo "Executing binary..."
+
+          ./scannercli scan -A 858361df98fa12fdeba836450120c0dcb22c3c97694db7fbeae607150ee42e9a -H https://e11d515bfb.cloud.aquasec.com nginx --registry {registry}
+
+          echo "Binary execution completed"
